### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by nicolae-stroncea** [cdrrazan/prasad#6]
Hey thanks for an amazing theme. I've set it up for my blog and it works and looks great!

I noticed that it doesn't seem to pick up highlighting.

**Steps I took to fix it**:
* I added a `syntax.css` file(got one from here [link](https://jwarby.github.io/jekyll-pygments-themes/languages/ruby.html)).
* Referenced it from `default.css`:  `<link href="{{ site.baseurl }}/assets/css/syntax.css" rel="stylesheet">`.

I know you have a syntax file already: `_sass\_syntax.cs` but it doesn't seem like it's getting recognized. I'm not too familiar with sass so it was much easier for me to fix it by adding a css version.

**Comment by cdrrazan** [comment]
Thanks @nicolae-stroncea for bringing this issue into the attention. I can see what you did to fix it. I will lookup to this issue ASAP and meanwhile it would be really good if you can submit the PR for this as well.
